services:
  web:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    expose:
      - 5000
    volumes:
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - FLASK_DEBUG=1
    networks:
      - app_network

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Changed to port 8080
    depends_on:
      - web
    volumes:
      - ./static:/app/static
      - ./media:/app/media
    networks:
      - app_network

networks:
  app_network: