"""like model adjustment to user model

Revision ID: 2db9eed2b44b
Revises: 5419fb0ecbde
Create Date: 2024-10-15 11:06:06.158978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db9eed2b44b'
down_revision = '5419fb0ecbde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('liked_posts')
        batch_op.drop_column('liked_comments')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('liked_comments', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('liked_posts', sa.TEXT(), nullable=True))

    # ### end Alembic commands ###
