"""Reinitializing migrations

Revision ID: 62c22cb246b4
Revises: 
Create Date: 2024-10-15 10:07:24.561679

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "62c22cb246b4"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key("fk_post_parent_id", "post", ["parent_id"], ["id"])

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("liked_comments", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("liked_comments")

    with op.batch_alter_table("post", schema=None) as batch_op:
        batch_op.drop_constraint("fk_post_parent_id", type_="foreignkey")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###