"""friends and requests

Revision ID: 9df7d8dd5787
Revises: 2db9eed2b44b
Create Date: 2024-10-18 19:19:10.468482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9df7d8dd5787'
down_revision = '2db9eed2b44b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('friend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('pending_requests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pending_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pending_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('received_requests',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('received_requests')
    op.drop_table('pending_requests')
    op.drop_table('friends')
    # ### end Alembic commands ###
